# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
@hospital_1 = Hospital.create!(name: 'Princeton-Plainsboro Teaching Hospital')
@hospital_2 = Hospital.create!(name: 'Sacred Heart Hospital')
@hospital_3 = Hospital.create!(name: 'New York Hospital')
@doctor_1 = @hospital_1.doctors.create!(name: 'Gregory House', specialty: 'Diagnostic Medicine', university: 'Johns Hopkins University')
@doctor_2 = @hospital_1.doctors.create!(name: 'Bob Kelso', specialty: 'General Medicine', university: 'Harvard University')
@doctor_3 = @hospital_2.doctors.create!(name: 'Christopher Turk', specialty: 'Surgery', university: 'Harvard University')
@doctor_4 = @hospital_3.doctors.create!(name: 'Steven Brule', specialty: 'Medicine', university: 'MIT')
@doctor_5 = @hospital_3.doctors.create!(name: 'Jan Itor', specialty: 'Medicine', university: 'MIT')
@patient_1 = Patient.create!(name: 'Rza', age: 24)
@patient_2 = Patient.create!(name: 'Gza', age: 39)
@patient_3 = Patient.create!(name: 'Method Man', age: 14)
@patient_4 = Patient.create!(name: 'Oh Deebee', age: 32)
@patient_5 = Patient.create!(name: 'Rae Kwon', age: 2)
@patient_6 = Patient.create!(name: 'Ghostface Killah', age: 75)
@patient_7 = Patient.create!(name: 'Inspectah Deck', age: 17)
@patient_8 = Patient.create!(name: 'Cappadonna', age: 35)
@patient_9 = Patient.create!(name: 'Masta Killa', age: 55)
@patient_10 = Patient.create!(name: 'U God', age: 45)
DoctorPatient.create!(doctor: @doctor_1, patient: @patient_1)
DoctorPatient.create!(doctor: @doctor_1, patient: @patient_2)
DoctorPatient.create!(doctor: @doctor_1, patient: @patient_3)
DoctorPatient.create!(doctor: @doctor_2, patient: @patient_4)
DoctorPatient.create!(doctor: @doctor_2, patient: @patient_5)
DoctorPatient.create!(doctor: @doctor_3, patient: @patient_6)
DoctorPatient.create!(doctor: @doctor_3, patient: @patient_7)
DoctorPatient.create!(doctor: @doctor_4, patient: @patient_8)
DoctorPatient.create!(doctor: @doctor_4, patient: @patient_9)
DoctorPatient.create!(doctor: @doctor_5, patient: @patient_10)
DoctorPatient.create!(doctor: @doctor_3, patient: @patient_1)
DoctorPatient.create!(doctor: @doctor_3, patient: @patient_2)